version: "3.8"

services:
  app:
    depends_on:
      - api
    build: ./client
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/pnpm-lock.yaml
          action: rebuild
        - path: ./client
          target: /app
          action: sync
    networks:
      - hackops-network

  api:
    build: ./server
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/pnpm-lock.yaml
          action: rebuild
        - path: ./server
          target: /app
          action: sync
    networks:
      - hackops-network

volumes:
  hackops:

networks:
  hackops-network:
    driver: bridge
