services:
  app:
    depends_on:
      - api
    build: ./client
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/pnpm-lock.yaml
          action: rebuild
        - path: ./client
          target: /app
          action: sync
    networks:
      - app-network

  api:
    build: ./server
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/pnpm-lock.yaml
          action: rebuild
        - path: ./server
          target: /app
          action: sync
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=:9090"
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - app-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  hackops:
  prometheus-data:
  grafana-data:
