global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "nestjs-app"
    metrics_path: "/api/v1/metrics"
    static_configs:
      - targets: ["hackops-api:8000"]
        labels:
          instance: "api-service"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance: "prometheus"
