global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nestjs-app"
    metrics_path: "/api/v1/metrics"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
