name: Deploy to VPS with Docker

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create server .env file
        run: |
          cd server
          echo "${{ secrets.SERVER_ENV }}" > .env

      - name: Create client .env file
        run: |
          cd client
          echo "${{ secrets.CLIENT_ENV }}" > .env

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker images
        run: |
          docker pull prodanish203/hackops-server:latest
          docker pull prodanish203/hackops-client:latest

      - name: Stop and remove existing containers
        run: docker compose down || true

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Reload Nginx
        run: sudo service nginx reload || sudo systemctl reload nginx

      - name: Prune unused Docker images
        run: docker image prune -f
