name: Deploy to VPS with Docker Compose

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create server .env file
        run: |
          cd server
          echo "${{ secrets.SERVER_ENV }}" > .env

      - name: Create client .env file
        run: |
          cd client
          echo "${{ secrets.CLIENT_ENV }}" > .env

      - name: Stop and remove existing containers
        run: sudo docker compose down || true

      - name: Build and start Docker Compose
        run: sudo docker compose up -d --build

      - name: Reload Nginx
        run: sudo service nginx reload || sudo systemctl reload nginx

      - name: Prune unused Docker images
        run: sudo docker image prune -f
